### ISSUE TITLE
Check Enchantment

### ISSUE THREAD

**Issue by Segysmundo** [PlaceholderAPI/CheckItem-Expansion#2]
If you had the time it would be nice to add the ability to check if the item has a specific enchantment or several enchantments. And to optionally specify the level of such enchantments.

Ex:
`%checkitem_enchant:DURABILITY%`
`%checkitem_enchant:KNOCKBACK:2%`
`%checkitem_enchant:KNOCKBACK:2;DURABILITY:3%`

The formatting above was just improvised by me for visualizing purposes.

Thanks in advance.

**Comment by cj89898** [comment]
Currently implemented in the most recent version of the source code.
I haven't pushed this to the eCloud yet due to some interesting interactions with the `strict` and `lorecontains` modifiers since apparently enchantments are counted as `lore`.

Will be working on fixing that, but if you would like to use the current version, [Click Here](https://www.dropbox.com/s/94zwu42n6129le5/Expansion-CheckItem.jar?dl=1) for a download

**Comment by Segysmundo** [comment]
So right now I would have to include the enchantment in lorecontains right?

How do you set multiple lines of the object for the lorecontains placeholder?

**Comment by cj89898** [comment]
I'm honestly not too sure how to set multiple lines, sorry for not seeing this sooner. You could try `\n` and that might work
