### ISSUE TITLE
Error when trying to parse item for getinfo

### ISSUE THREAD

**Issue by WataLaker37821** [PlaceholderAPI/CheckItem-Expansion#76]
Hello, i am gettimg errors while trying parse item (any item) using getinfo method for getting all item's nbts and other info displayed in chat/console

It looks like this: papi parse me %checkitem_getinfo:40% (on 1.21 it was displaying all item's info)

I am using:

- PlaceholderAPI: 2.11.7 DEV 200 (errors were on a latest stable release from spigot so i decided to get latest build)
- ItemNBTAPI: 2.13.2 
- Server version: Purpur 1.21.1 (build 2298)
- checkitem 2.7.7
[latest.log](https://github.com/user-attachments/files/16819063/latest.log)

In log file, errors start from line 948 and further

**Comment by cj89898** [comment]
Has not been updated for 1.21.1

**Comment by cj89898** [comment]
On second thought, after I've been able to do some testing on this..

It may have an issue to do with Purpur. I've just tested checkitem 2.7.7 on spigot without even updating NBTAPI to 2.13.2, still using 2.13.1, and everything works fine.

I have noticed in the changelog for 2.13.2 of NBTAPI says it fixes an issue with Paper, so this might also solve your issue. I'm not positive, because you stated in the original post that you tried 2.13.2.
